export const QUESTIONS_FOR_REPORTS = [
    "¿Cuál es la tasa de promesas de pago del asesor?",
    "¿Qué palabras o frases usan los asesores con mayor tasa de promesas de pago?",
    "¿Qué palabras usa el asesor que logra más acuerdos de recuperación de cartera?",
    "¿Cuántas llamadas terminan en acuerdos vs sin acuerdos?",
    "¿Qué duración promedio tienen las llamadas más exitosas vs no exitosas?",
    "¿Qué emociones predominan en las llamadas exitosas?",
    "¿Qué porcentaje de llamadas muestran al cliente enojado, frustrado o ansioso?",
    "¿En qué franja de mora y en que horarios de gestión hay más llamadas con emociones negativas y positivas?",
    "¿Qué emociones predominan en las llamadas de rechazo?",
    "¿Cuáles son las palabras que más generan rechazo o inconformidad en el cliente?",
    "¿Cuál es el sentimiento promedio de las llamadas en los diferentes horarios de llamada?",
    "¿Qué objeciones son más frecuentes en los clientes?",
    "¿Cuáles son las objeciones más frecuentes de los clientes?",
    "¿En que etapa de la llamada aparecen más objeciones?",
    "¿Qué asesores manejan mejor las objeciones?",
    "¿Cuántas llamadas terminan en perdida de calma con los clientes?",
    "¿Qué frases están asociadas a discusiones con los clientes?",
    "¿Qué duración promedio tienen las llamadas no efectivas?",
    "¿En qué momento se pierde más tiempo dentro de la llamada?",
    "¿Cuánto tiempo de silencio hay por llamada y quién lo genera?",
    "¿A qué horas del día hay llamadas efectivas?",
    "¿Cuántas llamadas se hacen en promedio por asesor sin resultado?",
    "¿Qué objeciones predominan en cartera temprana vs cartera castigada?",
    "¿Qué franja tiene mayor carga emocional negativa?",
    "¿Qué días de la semana hay más promesas de pago?",
    "¿Qué tipo de producto genera más conflicto?",
    "¿Qué tipo de acuerdo de recuperación de cartera es más solicitado y aceptado por los clientes?",
    "¿Qué tipo de acuerdo de recuperación de cartera es más rechazado por los clientes?",
    "¿Qué tipos de acuerdo de recuperación de cartera es más ofrecido vs los menos ofrecidos?",
];

// Conjunto de datasets disponibles para evaluación y chat (Auditbot)
// Nombre visible -> nombre de archivo esperado en /public
export const DATASET_CONFIG: Record<string, string> = {
    "Cobranzas Call": "resultados_evaluaciones_cobranzas.json",
    "Cobranzas Abogados": "resultados_evaluaciones_cobranzas_abogados.json",
    "Cobranzas Casa Mayor": "resultados_evaluaciones_cobranzas_casa_mayor.json",
    "Cobranzas Casa Menor": "resultados_evaluaciones_cobranzas_casa_menor.json",
    "Cobranzas Bot": "resultados_evaluaciones_cobranzas_bot.json",
};
